version: "3.8"

services:
  authentication:
    build:
      context: ./authentication_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - authentication_db

  authentication_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: baggr_authentication
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
