# Generated by Django 5.0.1 on 2024-01-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderproduct',
            name='image',
            field=models.ImageField(default='images/service_providers_products/default.png', help_text='Upload a product image', upload_to='images/service_providers_products/', verbose_name='Product Image'),
        ),
    ]
